options:
  n1kv-source:
    type: string
    default: distro
    description: |
      Optional configuration to support use of additional sources such as:
      .
        - If a private PPA deb http://my.archive.com/ubuntu main|KEYID
        - If a public PPA deb http://my.archive.com/ubuntu main
      .
      Note that this is used only for Cisco n1kv plugin.
  n1kv-version:
    type: string
    default: latest
    description: |
      Provides the vxlan gw image version. Default is the latest in the provided source.
