#!/bin/bash
# config-changed occurs everytime a new configuration value is updated (juju set)

function load_vxgw_to_glance {
  FILENAME=`ls /opt/cisco/n1kv/vxgw/*`

  if [ -f $FILENAME ]; then
    FILESIZE=$(stat -c%s "$FILENAME")
    IMG_NAME=$(basename $FILENAME)
    FILESIZE_LIMIT=118000000
    if [ "$FILESIZE" -lt "$FILESIZE_LIMIT" ]; then
      sleep 5
    fi
   
    openrc_ready=`cat /root/openrc | grep AUTH_URL | grep -oP '://\K.*?(?=/v2.0|$)'; true`
    TIMEOUT=60
    while [ "$openrc_ready" = ":" ]; do
      sleep 60
      TIMEOUT=$((TIMEOUT - 1))
      openrc_ready=`cat /root/openrc | grep AUTH_URL | grep -oP '://\K.*?(?=/v2.0|$)'; true`
      if [ "$TIMEOUT" -eq "0" ]; then
        exit 1
      fi
    done

    source /root/openrc

    img_exist=`glance image-list | grep -w $IMG_NAME; true`
    if [ "$img_exist" = "" ]; then
        glance image-create --name=$IMG_NAME --is-public=true --property hw_vif_model=virtio --property hw_disk_bus=ide --property hw_cdrom_bus=ide --container-format=ovf --disk-format=qcow2 < $FILENAME
    fi
  else
    exit 1
  fi
}

set -e
load_vxgw_to_glance
