#!/bin/bash
# This hook is executed each time a charm is upgraded after the new charm
# contents have been unpacked
# Best practice suggests you execute the hooks/install and
# hooks/config-changed to ensure all updates are processed

function download_vxgw {
  #remove already installed vxgw
  vxgw_installed=`apt-cache policy vxgw | grep Installed | grep -w none`
  if [ "$vxgw_installed" = "" ]; then
    apt-get remove -y vxgw
  fi
  rm -f /opt/cisco/n1kv/vxgw/*
  apt-get update
  version=$(config-get n1kv-version)

  if [ "$version" != "latest" ];then
    apt-get install -y vxgw="$version"*
  else
    apt-get install -y vxgw
  fi

  FILENAME=`ls /opt/cisco/n1kv/vxgw/*`
  while [ ! -f $FILENAME ]; do
    sleep 2
  done

  FILESIZE=$(stat -c%s "$FILENAME")
  FILESIZE_LIMIT=118000000
  if [ -f $FILENAME ]; then
    if [ "$FILESIZE" -lt "$FILESIZE_LIMIT" ]; then
        sleep 5
    fi
  fi
}

set -e 
download_vxgw

